***CHECKPOIN 1***

# **BUSINESS UNDERSTANDING**

## **Business Objective**

Objektif dari projek ini adalah untuk mencari pola dan memprediksi penyakit stroke berdasarkan faktor dan informasi kesehatan pasien guna membantu dokter dalam pengambilan keputusan medis yang tepat. Selain itu ini akan membantu dokter dalam memprioritaskan pasien dan efisiensi dalam perawatan.

## **Assess situation**

Kondisi di mana meningkatnya jumlah pasien dengan faktor dan risiko terkena stroke sementara terbatasnya tenaga medis dalan melakukan diagnosis dini menjadi tantangan utama yang harus diatasi. Selain itu kurangnya kesadaran akan gaya hidup tidak sehat seperti merokok, obesitas, kurang aktifitas fisik juga menjadi hal yang perlu diperhatikan. Dengan adanya analisis yang dilakukan diharapkan dapat mengatasi masalah ini.

## **Data Mining Goals**

Menemukan pola dalam faktor risiko dengan mengidentifikasi hubungan variable-variable medis dan kejadian stroke. Lalu, mengelompokkan pasien berdasarkan risiko stroke dan menganalisis efisiensi perawatannya.

## **Project Plan**

Tahapan atau rencana pengerjaannya:
1. Pengumpulan Data. Mengumpulkan dataset yang berisi resiko atau prediksi stroke. Variable yang dikumpulan seperti Usia, diabetes, BMI, riwayat merokok, aktifitas fisik, dan lain-lain yang sekiranya dibutuhkan. Lalu mencari informasi mengenai faktor risiko stroke.

2. Mempersiapkan dan Membersihkan Data. Tujuannya untuk mempersiapkan data untuk dianalisis.
Langkah-langkahnya bisa berupa:
- Mengatasi missing values atau data kosong.
- Menghapus atau menangani Outlier.
- Jika diperlukan, melakukan semacam standarisasi data.
- Mengubah data kategorial menjadi data numerik untuk memudahkan analisis jika diperlukan.

3. Exploratory Data Analysis (EDA). Pada dasarnya menganalisis data yang bertujuan untuk memahami distrubusi data, pola-polanya, dan korelasi antara variablenya. Hal ini meliputi Visualisasi data (Misal dengan Histogram, diagram, heatmap korelasi), Analisis stastistik, dan mengidenfikasi variable yang paling berpengaru terhadap risiko stroke.

4. Evaluasi. Menentukan model yang efisien dan efektif dalam kinerjanya. Lalu, mencoba model pada data real-world dan memantau performa model. Serta melakukan evaluasi tahapan plan dan menjadikan bahan informasi untuk kedepannya.

***CHECKPOIN 2***

## **Membaca Data**

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("/content/healthcare-dataset-stroke-data (1).csv")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

## **Memeriksa Tipe Data, jumlah baris, dan kolom**

In [6]:
df.dtypes

id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [7]:
df.shape

(5110, 12)

## **Statistik Deskriptif**

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [11]:
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [12]:
df.corr(numeric_only=True)

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
id,1.000000,0.003538,0.003550,-0.001296,0.001092,0.003084,0.006388
age,0.003538,1.000000,0.276398,0.263796,0.238171,0.333398,0.245257
hypertension,0.003550,0.276398,1.000000,0.108306,0.174474,0.167811,0.127904
heart_disease,-0.001296,0.263796,0.108306,1.000000,0.161857,0.041357,0.134914
avg_glucose_level,0.001092,0.238171,0.174474,0.161857,1.000000,0.175502,0.131945
bmi,0.003084,0.333398,0.167811,0.041357,0.175502,1.000000,0.042374
stroke,0.006388,0.245257,0.127904,0.134914,0.131945,0.042374,1.000000

# **DATA PREPARATION**

## **Data Cleaning**

### **Mencari missing value**

In [14]:
(df.isnull().sum() / len(df)) *100

id                   0.000000
gender               0.000000
age                  0.000000
hypertension         0.000000
heart_disease        0.000000
ever_married         0.000000
work_type            0.000000
Residence_type       0.000000
avg_glucose_level    0.000000
bmi                  3.933464
smoking_status       0.000000
stroke               0.000000
dtype: float64

Karena nilai bmi terdapat missing value, ada dua pilihan yang bisa dilakukan. Antara menghapusnya atau melakukan imputasi. Karena nilai missing value-nya jauh dari 70% maka saya memilih melakukan imputasi.

Mengecek distribusiinya

In [16]:
df['bmi'].describe()

count    4909.000000
mean       28.893237
std         7.854067
min        10.300000
25%        23.500000
50%        28.100000
75%        33.100000
max        97.600000
Name: bmi, dtype: float64

Melakukan imputasi dengan median.

In [51]:
df['bmi'] = df['bmi'].fillna(df['bmi'].median())

### **Mengecek Duplicate value**

In [52]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke, bmi_type]
Index: []

Karena tidak ada duplicate value maka tidak perlu ada tindakan lebih lanjut.

### **Mengecek kolom yang memiliki outlier**

In [53]:
numerical_columns = df.select_dtypes(include=['number']).columns

outlier_columns = []

for col in numerical_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    if not outliers.empty:
        outlier_columns.append(col)

print("Kolom yang memiliki outliers:", outlier_columns)

Kolom yang memiliki outliers: ['hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke']

### **Incosistent Value**

In [54]:
df.head(51)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,bmi_type
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,float
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1,float
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,float
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,float
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,int
5,56669,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1,int
6,53882,Male,74.0,1,1,Yes,Private,Rural,70.09,27.4,never smoked,1,float
7,10434,Female,69.0,0,0,No,Private,Urban,94.39,22.8,never smoked,1,float
8,27419,Female,59.0,0,0,Yes,Private,Rural,76.15,28.1,Unknown,1,float
9,60491,Female,78.0,0,0,Yes,Private,Urban,58.57,24.2,Unknown,1,float
10,12109,Female,81.0,1,0,Yes,Private,Rural,80.43,29.7,never smoked,1,float
11,12095,Female,61.0,0,1,Yes,Govt_job,Rural,120.46,36.8,smokes,1,float
12,12175,Female,54.0,0,0,Yes,Private,Urban,104.51,27.3,smokes,1,float
13,8213,Male,78.0,0,1,Yes,Private,Urban,219.84,28.1,Unknown,1,float
14,5317,Female,79.0,0,1,Yes,Private,Urban,214.09,28.2,never smoked,1,float
15,58202,Female,50.0,1,0,Yes,Self-employed,Rural,167.41,30.9,never smoked,1,float
16,56112,Male,64.0,0,1,Yes,Private,Urban,191.61,37.5,smokes,1,float
17,34120,Male,75.0,1,0,Yes,Private,Urban,221.29,25.8,smokes,1,float
18,27458,Female,60.0,0,0,No,Private,Urban,89.22,37.8,never smoked,1,float
19,25226,Male,57.0,0,1,No,Govt_job,Urban,217.08,28.1,Unknown,1,float
20,70630,Female,71.0,0,0,Yes,Govt_job,Rural,193.94,22.4,smokes,1,float
21,13861,Female,52.0,1,0,Yes,Self-employed,Urban,233.29,48.9,never smoked,1,float
22,68794,Female,79.0,0,0,Yes,Self-employed,Urban,228.70,26.6,never smoked,1,float
23,64778,Male,82.0,0,1,Yes,Private,Rural,208.30,32.5,Unknown,1,float
24,4219,Male,71.0,0,0,Yes,Private,Urban,102.87,27.2,formerly smoked,1,float
25,70822,Male,80.0,0,0,Yes,Self-employed,Rural,104.12,23.5,never smoked,1,float
26,38047,Female,65.0,0,0,Yes,Private,Rural,100.98,28.2,formerly smoked,1,float
27,61843,Male,58.0,0,0,Yes,Private,Rural,189.84,28.1,Unknown,1,float
28,54827,Male,69.0,0,1,Yes,Self-employed,Urban,195.23,28.3,smokes,1,float
29,69160,Male,59.0,0,0,Yes,Private,Rural,211.78,28.1,formerly smoked,1,float
30,43717,Male,57.0,1,0,Yes,Private,Urban,212.08,44.2,smokes,1,float
31,33879,Male,42.0,0,0,Yes,Private,Rural,83.41,25.4,Unknown,1,float
32,39373,Female,82.0,1,0,Yes,Self-employed,Urban,196.92,22.2,never smoked,1,float
33,54401,Male,80.0,0,1,Yes,Self-employed,Urban,252.72,30.5,formerly smoked,1,float
34,14248,Male,48.0,0,0,No,Govt_job,Urban,84.20,29.7,never smoked,1,float
35,712,Female,82.0,1,1,No,Private,Rural,84.03,26.5,formerly smoked,1,float
36,47269,Male,74.0,0,0,Yes,Private,Rural,219.72,33.7,formerly smoked,1,float
37,24977,Female,72.0,1,0,Yes,Private,Rural,74.63,23.1,formerly smoked,1,float
38,47306,Male,58.0,0,0,No,Private,Rural,92.62,32.0,Unknown,1,int
39,62602,Female,49.0,0,0,Yes,Private,Urban,60.91,29.9,never smoked,1,float
40,4651,Male,78.0,0,0,Yes,Private,Rural,78.03,23.9,formerly smoked,1,float
41,1261,Male,54.0,0,0,Yes,Private,Urban,71.22,28.5,never smoked,1,float
42,61960,Male,82.0,0,1,Yes,Private,Urban,144.90,26.4,smokes,1,float
43,1845,Female,63.0,0,0,Yes,Private,Urban,90.90,28.1,formerly smoked,1,float
44,7937,Male,60.0,1,0,Yes,Govt_job,Urban,213.03,20.2,smokes,1,float
45,19824,Male,76.0,1,0,Yes,Private,Rural,243.58,33.6,never smoked,1,float
46,37937,Female,75.0,0,1,No,Self-employed,Urban,109.78,28.1,Unknown,1,float
47,47472,Female,58.0,0,0,Yes,Private,Urban,107.26,38.6,formerly smoked,1,float
48,35626,Male,81.0,0,0,Yes,Self-employed,Urban,99.33,33.7,never smoked,1,float
49,36338,Female,39.0,1,0,Yes,Private,Rural,58.09,39.2,smokes,1,float
50,18587,Female,76.0,0,0,No,Private,Urban,89.96,28.1,Unknown,1,float

In [55]:
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,bmi_type
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,float
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1,float
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,float
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,float
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,int
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,28.1,never smoked,0,float
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,int
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,float
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,float
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,float

Mencari nilai unik

In [56]:
for col in df.select_dtypes(include=['object']).columns:
    print(f"Kolom: {col}")
    print(df[col].unique(), "\n")

Kolom: gender
['Male' 'Female' 'Other']

Kolom: ever_married
['Yes' 'No']

Kolom: work_type
['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked']

Kolom: Residence_type
['Urban' 'Rural']

Kolom: smoking_status
['formerly smoked' 'never smoked' 'smokes' 'Unknown']

Kolom: bmi_type
['float' 'int']

Mengecek inkonsistensi angka (semisal nilai bmi)

In [57]:
df['bmi_type'] = df['bmi'].apply(lambda x: 'int' if x == int(x) else 'float')
print(df['bmi_type'].value_counts())

bmi_type
float    4623
int       487
Name: count, dtype: int64

In [71]:
print(df[df['bmi_type'] == 'int']['bmi'].value_counts())

bmi
27.0    35
24.0    28
28.0    28
25.0    27
23.0    27
30.0    27
29.0    26
26.0    25
31.0    22
32.0    21
34.0    17
20.0    17
21.0    17
18.0    16
33.0    15
22.0    15
38.0    13
35.0    12
36.0    11
37.0    10
17.0    10
16.0     8
43.0     8
39.0     7
19.0     7
40.0     6
45.0     5
46.0     4
44.0     4
41.0     3
42.0     3
55.0     2
15.0     2
48.0     1
92.0     1
13.0     1
51.0     1
54.0     1
56.0     1
78.0     1
12.0     1
14.0     1
Name: count, dtype: int64

Karena angka integer nya gak terlalu banyak, aku mencurigai bahwa ini adalah angka dari hasil imputasi kolom bmi sebelumnya.

Mengecek nilai integer sebelum imputasi dan sesudah.

In [72]:
print(df['bmi'].isna().sum())  #Untuk cek jumlah missing value sebelum diimputasi
print(df[df['bmi_type'] == 'int'].shape[0])  #Untuk Cek jumlah nilai missing value integer sekarang

0
487

Nah kan, kayaknya ini emang nilai dari imputasi sebelumnya. Supaya lebih konsisten, tipe datanya diubah semuanya ke tipe float.

In [79]:
df.loc[df['bmi'] % 1 == 0, 'bmi'] = df['bmi'].astype(float)

In [76]:
print(df['bmi'].apply(type).value_counts())

bmi
<class 'float'>    5110
Name: count, dtype: int64

### **Melakukan Construct Data**

Menambahkan kolom baru. Semisalnya skor resiko hipertensi dan sakit jantung.

In [80]:
df['risk_score'] = df['hypertension'] + df['heart_disease']

In [81]:
print(df[['hypertension', 'heart_disease', 'risk_score']].head(10))

   hypertension  heart_disease  risk_score
0             0              1           1
1             0              0           0
2             0              1           1
3             0              0           0
4             1              0           1
5             0              0           0
6             1              1           2
7             0              0           0
8             0              0           0
9             0              0           0

In [82]:
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,bmi_type,risk_score
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,float,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1,float,0
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,float,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,float,0
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,int,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,28.1,never smoked,0,float,1
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,int,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,float,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,float,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,float,0

### **Data Reduction**

Menghapus kolom yang tidak relevan dengan studi kasus yang diambil. Dalam studi kasus kali ini yakni bertema "*Stroke Prediction*" maka kolom id tidak akan berpengaruh pada hasil analisis ke tema ini.

Menghapus kolom id

In [83]:
df.drop(columns=['id'], inplace=True)

In [85]:
print(df.columns)

df

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke', 'bmi_type', 'risk_score'],
      dtype='object')

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,bmi_type,risk_score
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,float,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1,float,0
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,float,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,float,0
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,int,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.1,never smoked,0,float,1
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,int,0
5107,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,float,0
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,float,0
5109,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,float,0